version: '3.8'

services:

  mySQL:
    image: mysql:latest
    restart: always
    container_name: agil_services
    environment:
      - MYSQL_DATABASE=pw_servicios
      - MYSQL_ROOT_PASSWORD=agiles123!!

    ports:
      - '3307:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql